### ISSUE TITLE
Point to release build of `smode_laser` Rust library

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#18]
Currently we're still linking to the debug build of the static library for testing. We should make sure we're pointing to the release build before we consider this finished. Alternatively, maybe there's some way to select between the two in cmake depending on the target being built?

**Comment by francis-maes** [comment]
Assigning @Qlex42, because he will be able to help you on Cmake stuff

**Comment by mitchmindtree** [comment]
Ahh that would be great! [This is the line](https://github.com/MindBuffer/smode_laser_plugin/blob/ccea3c75fd590577d1ebb65abfad4686d86551bd/plugin/CMakeLists.txt#L32) in the CMakeLists where we currently assume debug. @Qlex42  I wonder if we should check some condition here to select between debug or release static lib instead?

**Comment by Qlex42** [comment]
Hi Mitch !

CMake offer special TARGET_LINK_LIBRARIES parameters (debug and optimized) for that:

`target_link_libraries(Laser debug "${PLUGIN_DEBUG_LIB_PATH}/smode_laser.lib" optimized "${PLUGIN_RELEASE_LIB_PATH}/smode_laser.lib")`

hoping this can helps

**Comment by mitchmindtree** [comment]
Perfect, thanks @Qlex42 !
