### ISSUE TITLE
Solve crash that occurs when DAC unexpectedly stops responding via TCP

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#19]
We're not yet handling the case where the TCP stream is disconnected for some reason e.g. network issues, the DAC is turned off, etc. Need to make sure we can handle this and provide some feedback to the user somehow.

**Comment by francis-maes** [comment]
we already did this in several devices. I can show you how it is handled in other cases.
Note: Device has a "SuccessStatus" variable that enables to report disconnection errors

**Comment by mitchmindtree** [comment]
Thanks yes an example would be great!

**Comment by mitchmindtree** [comment]
Reminder for myself - see `Device.h` `SuccessStatus.h`:
```cpp

  // Status
  const SuccessStatus& getStatus() const
    {return status;}
  SuccessStatus& getStatus()
    {return status;}

  void setStatusFromSmodeThread(const SuccessStatus& status);
  void setStatusFromOtherThread(const SuccessStatus& status);
```
