### ISSUE TITLE
Test running multiple unique DACs at the same time

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#22]
So far we've only tested running a single DAC. In theory, everything should "just work" for multiple DACs but we should check to be sure. This includes using two separate "LaserRenderer"s and targeting both DACs separately.

**Comment by francis-maes** [comment]
can be tested with the simulator?
Could you please add access to the repo to user https://github.com/RBasile ?
He is our beta-tester and will help beta-testing everything.

**Comment by mitchmindtree** [comment]
Yes this can be tested by running multiple instances of the DAC emulator, however the MAC address should be changed on each instance in the code. I'll be sure to mention how to do this when we update the README with steps as mentioned in #17. Happy to add @RBasile!

**Comment by JoshuaBatty** [comment]
[this PR](https://github.com/nannou-org/nannou/pull/543) to nannou laser fixes an issue that now means we can stream unique points to each connected DAC.
