### ISSUE TITLE
Test the `add_points` functionality

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#23]
So far we've only tested the `add_lines` functionality as this is what we are currently provided with from the `LaserGeometryRenderer`. We should double check that `add_points` works just as well.

**Comment by francis-maes** [comment]
I was thinking that if this transformation is required by every laser, it should probably be handled on the LaserGeometryRenderer side (this enable to expose any property we want in the process of creating the final sequence of laser points, and this makes the "device" part simpler).
Open to discussion :)

**Comment by mitchmindtree** [comment]
Yes that is totally fine. In the Rust code, we actually implement `add_points` in terms of `add_lines` as points are just lines that start and end in the same position with blank lines between them. [Here](https://github.com/nannou-org/nannou/blob/04821927461411ce3aa6e3ca1cef03cfd7b1a6e0/nannou_laser/src/stream/frame/mod.rs#L319-L322) is where we implement `add_points` in the Rust code in case you are interested.

**Comment by francis-maes** [comment]
As discussed together, let's close this one and push this question to the LaserGeometryRenderer.
