### ISSUE TITLE
Test with both version 1 and 2 Ether Dream DACs

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#24]
Currently we have only been testing with the ether dream DAC emulator. We should test with both releases of the real Ether Dream DAC when they arrive in our possession as both have subtle quirks in their TCP communication.

**Comment by francis-maes** [comment]
clear! We also ordered a laser but just learned that post services are temporarely shutdown, so no idea when it will receive it.

**Comment by mitchmindtree** [comment]
We will have both versions to test with once Josh's wife arrives back in Berlin from her flight (very soon) so we should be able to test this early next week. That said we are also awaiting some ILDA cables, hopefully our post does not get shut down too!

**Comment by JoshuaBatty** [comment]
Just tested both version 1 and version 2 of the etherdream DACs and they both work perfectly.
