### ISSUE TITLE
Dynamically set the min and max for `LaserDevice` variables and have the bounds reflected in the GUI

### ISSUE THREAD

**Issue by mitchmindtree** [MindBuffer/smode_laser_plugin#29]
The exact limits of a LASER device are not always known until it has been discovered. In the case of the Ether Dream protocol, a DAC includes its capabilities and limitations within its broadcast message. It would be nice if these limits could be reflected in the range of the GUI widget for each of these parameters. Currently, @JoshuaBatty and I are only aware of how to set the bounds for a variable statically (in the XML) - is there a way we can update these bounds dynamically? If so, would it be possible to see a code of example of how this is achieved? cc @francis-maes @Qlex42 

Specifically, the two variables we are most concerned with are the `pointsPerSecond` and `latencyPoints`. Points per second is the rate at which the DAC can receive and emit points per second. The reported limit can be anywhere from 10,000 to 100,000. The `latencyPoints` represents the size of the buffer that the DAC should use for buffering points received over the network. The greater the value, the less chance there is of dropout at the cost of introducing more latency. The maximum buffer size is also reported by the DAC.

**Comment by francis-maes** [comment]
That is the way to go:

@laurentmeyer, maybe this snippet could be added to the documentation somewhere.

```
class SomeClass : public Object
{
public:
  void variableChangedCallback(Object* variable, Object* changedObject) override
  {
     if (variable == &valueToConstrain && !isApplyingVariableConstraints())
     {
       VariableConstraintsScope _(*this);
        double runtimeMin = ...;
        double runtimeMax = ...;
        if (valueToConstrain < runtimeMin)
            valueToConstrain.set(runtimeMin);
        if (valueToConstrain > runtimeMax)
            valueToConstrain.set(runtimeMax);
      }
     BaseClass::variableChangedCallback(variable, changedObject);
  }
private:
  Real valueToConstrain;
};
```
